### ISSUE TITLE
Support `dep.js`

### ISSUE THREAD

**Issue by jthegedus** [ebebbington/depcheck#31]
## Summary

I use `.js` files with [JSDoc](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) for typing, therefore all my deps are listed in `deps.js`, not `deps.ts` and this project errors on the file extension as it cannot find `deps.ts`

**Comment by ebebbington** [comment]
I’ll add a feature tonight to pass in a file name that will be used instead :) eg `depcheck —dep-file=deps.js`

**Comment by ebebbington** [comment]
@jthegedus sorted :) `deno run --allow-read='.' https://deno.land/x/depcheck@v2.1.0/mod.ts deps.js`
